version: '3.8'

services:
  backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mysql_data:
